/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.taras_grynchuk.oop.forms;

import com.taras_grynchuk.oop.Car;
import com.taras_grynchuk.oop.ListOfCars;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author Taras
 */
public class CheapestForm extends javax.swing.JFrame {
    private ListOfCars cars; 
    /**
     * Creates new form CheapestForm
     */
    public CheapestForm(ListOfCars cars) {
        this.cars = cars;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modelLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        goButton = new javax.swing.JButton();
        priceLabel = new javax.swing.JLabel();
        priceLabelTitle = new javax.swing.JLabel();
        powerLabelTitle = new javax.swing.JLabel();
        powerLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Найдешевша та найменш потужна");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setResizable(false);

        modelLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        modelLabel.setText("Марка:");
        modelLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jComboBox1.setModel(new DefaultComboBoxModel(cars.getArrayOfModels()));

        goButton.setText("Знайти");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        priceLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(51, 175, 128));
        priceLabel.setText("< ... >");
        priceLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        priceLabelTitle.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        priceLabelTitle.setForeground(new java.awt.Color(51, 175, 128));
        priceLabelTitle.setText("Найдешевша:");
        priceLabelTitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        powerLabelTitle.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        powerLabelTitle.setForeground(new java.awt.Color(227, 37, 66));
        powerLabelTitle.setText("Найменш потужна:");
        powerLabelTitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        powerLabelTitle.setMaximumSize(new java.awt.Dimension(85, 17));
        powerLabelTitle.setMinimumSize(new java.awt.Dimension(85, 17));
        powerLabelTitle.setPreferredSize(new java.awt.Dimension(85, 17));

        powerLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        powerLabel.setForeground(new java.awt.Color(227, 37, 66));
        powerLabel.setText("< ... >");
        powerLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(priceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(modelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, 0, 398, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(goButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(priceLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(powerLabelTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(powerLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(powerLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(powerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        // TODO add your handling code here:
        int priceInd = cars.getMinPriceIndex(jComboBox1.getModel().getSelectedItem().toString());
        priceLabel.setText((priceInd < 0 ? "< не знайдено >" : 
                "№ " + (1+priceInd) + ". " + cars.get(priceInd)));
        
        int powerInd = cars.getMinPowerIndex(jComboBox1.getModel().getSelectedItem().toString());
        powerLabel.setText((powerInd < 0 ? "< не знайдено >" : 
                "№ " + (1+powerInd) + ". " + cars.get(powerInd)));
    }//GEN-LAST:event_goButtonActionPerformed

  
    public static void open(ListOfCars cars) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheapestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheapestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheapestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheapestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CheapestForm(cars).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton goButton;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JLabel powerLabel;
    private javax.swing.JLabel powerLabelTitle;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel priceLabelTitle;
    // End of variables declaration//GEN-END:variables
}
